"""Prisma schema and seed script generation."""

from __future__ import annotations

import json
from typing import Any, Dict, List


def generate_prisma_schema(
    posts: List[Dict[str, Any]],
    participants: List[Dict[str, Any]],
) -> str:
    """Generate Prisma schema from crawl data."""
    return """// Prisma schema generated by WebPort

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Post {
  id              Int      @id
  slug            String   @unique
  title           String
  content         String
  excerpt         String?
  date            DateTime?
  status          String   @default("publish")
  featuredMediaUrl String?
  audioFile       String?
  participants    PostParticipant[]
  categories      PostCategory[]
  tags            PostTag[]
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt
}

model Participant {
  id                Int      @id
  slug              String   @unique
  name              String
  content           String?
  professionalTitle String?
  featuredMediaUrl  String?
  posts             PostParticipant[]
  createdAt         DateTime @default(now())
  updatedAt         DateTime @updatedAt
}

model PostParticipant {
  post          Post        @relation(fields: [postId], references: [id])
  postId        Int
  participant   Participant @relation(fields: [participantId], references: [id])
  participantId Int

  @@id([postId, participantId])
}

model Category {
  id    Int    @id
  name  String
  slug  String @unique
  posts PostCategory[]
}

model Tag {
  id    Int    @id
  name  String
  slug  String @unique
  posts PostTag[]
}

model PostCategory {
  post       Post     @relation(fields: [postId], references: [id])
  postId     Int
  category   Category @relation(fields: [categoryId], references: [id])
  categoryId Int

  @@id([postId, categoryId])
}

model PostTag {
  post   Post @relation(fields: [postId], references: [id])
  postId Int
  tag    Tag  @relation(fields: [tagId], references: [id])
  tagId  Int

  @@id([postId, tagId])
}

model Page {
  id       Int    @id
  slug     String @unique
  title    String
  content  String
  parentId Int?
}
"""


def generate_seed_script(
    posts: List[Dict[str, Any]],
    participants: List[Dict[str, Any]],
) -> str:
    """Generate Prisma seed script."""
    return """import { PrismaClient } from '@prisma/client'
import * as fs from 'fs'
import * as path from 'path'

const prisma = new PrismaClient()

function loadJson(filename: string) {
  const filePath = path.join(__dirname, '../../input', filename)
  if (!fs.existsSync(filePath)) return []
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'))
}

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '').trim()
}

async function main() {
  console.log('Seeding database...')

  const posts = loadJson('wp_posts.json')
  const participants = loadJson('wp_participants.json')
  const categories = loadJson('wp_categories.json')
  const tags = loadJson('wp_tags.json')
  const pages = loadJson('wp_pages.json')
  const relationships = loadJson('roundtable_participants.json')
  const titles = loadJson('participant_titles.json')

  // Seed categories
  for (const cat of categories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: {},
      create: { id: cat.id, name: cat.name, slug: cat.slug },
    })
  }
  console.log(`Seeded ${categories.length} categories`)

  // Seed tags
  for (const tag of tags) {
    await prisma.tag.upsert({
      where: { id: tag.id },
      update: {},
      create: { id: tag.id, name: tag.name, slug: tag.slug },
    })
  }
  console.log(`Seeded ${tags.length} tags`)

  // Build title lookup
  const titleMap = new Map<string, string>()
  for (const t of titles) {
    if (t.professional_title) {
      titleMap.set(t.slug, t.professional_title)
    }
  }

  // Seed participants
  for (const p of participants) {
    const title = p.title?.rendered || p.title || ''
    await prisma.participant.upsert({
      where: { id: p.id },
      update: {},
      create: {
        id: p.id,
        slug: p.slug,
        name: stripHtml(title),
        content: p.content?.rendered || p.content || '',
        professionalTitle: titleMap.get(p.slug) || null,
        featuredMediaUrl: p.featured_media_url || null,
      },
    })
  }
  console.log(`Seeded ${participants.length} participants`)

  // Seed posts
  for (const post of posts) {
    const title = post.title?.rendered || post.title || ''
    await prisma.post.upsert({
      where: { id: post.id },
      update: {},
      create: {
        id: post.id,
        slug: post.slug,
        title: stripHtml(title),
        content: post.content?.rendered || post.content || '',
        excerpt: post.excerpt?.rendered || post.excerpt || null,
        date: post.date ? new Date(post.date) : null,
        status: post.status || 'publish',
        featuredMediaUrl: post.featured_media_url || null,
        audioFile: post.meta?.audio_file || null,
      },
    })

    // Post categories
    for (const catId of (post.categories || [])) {
      try {
        await prisma.postCategory.create({
          data: { postId: post.id, categoryId: catId },
        })
      } catch {}
    }

    // Post tags
    for (const tagId of (post.tags || [])) {
      try {
        await prisma.postTag.create({
          data: { postId: post.id, tagId: tagId },
        })
      } catch {}
    }
  }
  console.log(`Seeded ${posts.length} posts`)

  // Seed relationships
  for (const rel of relationships) {
    const post = posts.find((p: any) => p.slug === rel.slug)
    if (!post) continue
    for (const related of (rel.related || [])) {
      const participant = participants.find((p: any) => p.slug === related.slug)
      if (!participant) continue
      try {
        await prisma.postParticipant.create({
          data: { postId: post.id, participantId: participant.id },
        })
      } catch {}
    }
  }
  console.log('Seeded relationships')

  // Seed pages
  for (const page of pages) {
    const title = page.title?.rendered || page.title || ''
    await prisma.page.upsert({
      where: { id: page.id },
      update: {},
      create: {
        id: page.id,
        slug: page.slug,
        title: stripHtml(title),
        content: page.content?.rendered || page.content || '',
        parentId: page.parent || null,
      },
    })
  }
  console.log(`Seeded ${pages.length} pages`)

  console.log('Done!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
"""
